spring.application.name=dog-api
# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/dog_api
spring.datasource.username=postgres
spring.datasource.password=249513

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
